apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.fullname }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service.name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
