services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - VITE_IDP_API_URL=http://localhost:8000
      - VITE_API_URL=http://localhost:8080
      - VITE_CLIENT_ID=locus-frontend-client