auth:
  username: program
  password: test
  database: loyalties

primary:
  persistence:
    enabled: false
  initdbScripts:
    01-schema.sql: |
      CREATE TABLE IF NOT EXISTS loyalty (
          id SERIAL PRIMARY KEY,
          username VARCHAR(80) NOT NULL UNIQUE,
          reservation_count INT NOT NULL DEFAULT 0,
          status VARCHAR(80) NOT NULL DEFAULT 'BRONZE'
              CHECK (status IN ('BRONZE', 'SILVER', 'GOLD')),
          discount INT NOT NULL
      );

      INSERT INTO loyalty (username, reservation_count, status, discount)
      VALUES ('Test', 25, 'GOLD', 10)
      ON CONFLICT (username) DO NOTHING;

      INSERT INTO loyalty (username, reservation_count, status, discount)
      VALUES ('admin', 20, 'GOLD', 10)
      ON CONFLICT (username) DO NOTHING;
