auth:
  username: program
  password: test
  database: payments

primary:
  persistence:
    enabled: false
  initdbScripts:
    01-schema.sql: |
      CREATE TABLE payment
      (
          id          SERIAL PRIMARY KEY,
          payment_uid uuid        NOT NULL,
          status      VARCHAR(20) NOT NULL
              CHECK (status IN ('PAID', 'CANCELED')),
          price       INT         NOT NULL
      );
