auth:
  username: program
  password: test
  database: payments

primary:
  persistence:
    enabled: true
    size: 1Gi

  initdb:
    user: program        
    password: test
    scripts:
      10-create-tables.sql: |
        CREATE TABLE IF NOT EXISTS payment
        (
            id           SERIAL      PRIMARY KEY,
            payment_uid  uuid        NOT NULL UNIQUE,
            status       VARCHAR(20) NOT NULL CHECK (status IN ('PAID', 'CANCELED')),
            price        INT         NOT NULL
        );

