replicaCount: 1

kraft:
  enabled: true

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT

advertisedListeners:
  client:
    protocol: PLAINTEXT

allowPlaintextListener: true

persistence:
  enabled: false
