replicaCount: 1

image:
  repository: tonynm/gateway_service
  tag: latest
  pullPolicy: Always

service:
  fullname: gateway-service
  name: gateway
  port: 8080

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"

ingress:
  enabled: true
  name: gateway-ingress
  path: /api/v1
