replicaCount: 1

image:
  repository: tonynm/loyalty_service
  tag: latest
  pullPolicy: Always

service:
  fullname: loyalty-service
  name: loyalty
  port: 8050

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"

ingress:
  enabled: false
